### ISSUE TITLE
Loading trained checkpoints

### ISSUE THREAD

**Issue by ozturkoktay** [HasnainRaz/Fast-SRGAN#16]
Hi Hasnain, thank you for great work. I'm training network with larger dataset and in your code you are save models for every two hundred iterations. When train ends should I load the latest generator checkpoint file or should I do something different?

**Comment by HasnainRaz** [comment]
Hey,

I see you closed this issue, but in case you wanted an answer:
I used the latest generator, because I didn't see the model diverging. The other reason being I didn't use a validation set, I eye balled the results on tensorboard and stopped training when I liked the results and used that checkpoints.
