### ISSUE TITLE
is there any plan to port the SR model onto a mobile phone?

### ISSUE THREAD

**Issue by ColdCodeCool** [HasnainRaz/Fast-SRGAN#23]
Thank you for your great work. I was wondering if you have any plan to port the sr models onto a mobile phone? And do you think SR models on mobile devices can run in real-time?

**Comment by HasnainRaz** [comment]
I currently am trying to port this to a mobile device, though this will only happen after I'm finished with the PyTorch migration #21 

Though I don't think we can come close to anywhere real time on mobile devices, since currently it super resolves in realtime to 720p on a GPU.
Maybe CoreML is an option to speed it up on mobile. But I haven't explored this option very well.
