### ISSUE TITLE
pre-trained model D (Discriminator) not found

### ISSUE THREAD

**Issue by brenoslinhares** [HasnainRaz/Fast-SRGAN#28]
Hello Hasnain, good morning!

First of all, congratulations on the project. I have a doubt about the .h5 file of the pre-trained model of D (Discriminator), which I did not find in the models folder. Is there any reason for not having this file and only having the pre-trained model G (Generator)?
From what I understand, the GAN network only uses the pre-trained G model for test operation. Is there any particularity in this type of operation?

Thanks!

**Comment by HasnainRaz** [comment]
Hey,

Thank you for your interest. The discriminator is only needed during training. The generator is trained to do super resolution, while the discriminator can be thought of as helping the generator learn. Hence, once the generator has learned, there is no need for it. At test time, we only feed images into the generator to get the super resolved version at the output. I didn't include the weights for the discriminator because of this reason, since they would be useless for anyone trying out the demo.
