### ISSUE TITLE
Image Quality Not That Great

### ISSUE THREAD

**Issue by nerdogram** [HasnainRaz/Fast-SRGAN#5]
The output images don't seem to have  the same quality as some other SR-GAN Models. In particular...when you zoom in you can see blurry/overly smooth pixels. Have you tried doing this on ESRGAN...maybe that will lead to better results?

**Comment by HasnainRaz** [comment]
Yep, that is the price to pay for having a faster model, we lose out on quality.

Implementing ESRGAN tricks is on the todo list, but I will imagine that it wouldn't be close to the original ESRGAN because our model is much smaller.

The goal for me for this project was to do better than traditional upsampling, which it does.

**Comment by nerdogram** [comment]
Gotcha. Yeah I agree it is fast...however the memory requirements cause it to still not be viable on a simple cpu for inference :/
I am going to try splitting the image to see if that works
